# -*- coding: utf-8 -*-
# Generated by Django 1.9.6 on 2016-08-24 03:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recoapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Attachment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('parent_id', models.CharField(max_length=18)),
                ('file_name', models.CharField(max_length=100)),
                ('attachment', models.FileField(upload_to=b'documents/%Y/%m/%d')),
            ],
        ),
    ]
